In [1]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv('data/MDSF_data.csv', encoding = "ISO-8859-1", low_memory=False)
servicetypes = ["Support Service", "Care Home Service", "Offender Accommodation Service", "Housing Support Service"] 

# drop = ["Address_line_1", \
#         "Address_line_2", \
#         "Address_line_3",  \
#         "Address_line_4", \
#         "ManagerName", \
#         "Service_Phone_Number", \
#         "Eforms_email_address", \
#         "Date_Reg", \
#         "Care_Home_All_Areas_of_Provision", \
#         "Year_Month_latest_grade", \
#         "MinGrade_change", \
#         "CS_Wellbeing_change", \
#         "CS_Planning_change", \
#         "Setting_change", \
#         "Staff_change", \
#         "Leadership_change", \
#         "any_requirements_1617", \
#         "any_requirements_1718", \
#         "any_requirements_1819"]

# df = df.drop(drop, axis=1)

df = df[df['CareService'].isin(servicetypes)]
df.head()

,CSNumber,Combined_Service_,CaseNumber_Combined,CareService,Subtype,ServiceType,ServiceName,Address_line_1,Address_line_2,Address_line_3,...,second_recs_1819,second_reqs_1819,third_date_1819,third_case_1819,third_recs_1819,third_reqs_1819,fourth_date_1819,fourth_case_1819,fourth_recs_1819,fourth_reqs_1819
3,CS2003000150,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Threshold Glasgow Day Opportunities,Templeton Business Centre,"Building 5, Unit 5",The Doges,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CS2003000153,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Aviv Club,Walton Community Care Centre,May Terrace,Giffnock,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CS2003000161,NaN,NaN,Care Home Service,Learning Disabilities,Voluntary or Not for Profit,Richmondhill House,18 Richmondhill Place,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CS2003000164,NaN,NaN,Care Home Service,Older People,Voluntary or Not for Profit,Ruthrieston House,199 Broomhill Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CS2003000168,NaN,NaN,Care Home Service,Mental Health Problems,Voluntary or Not for Profit,Arrdeir,Arrdeir House,Oakdale Terrace,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# id_vars = ["CSNumber", 
# "Combined_Service_",
# "CaseNumber_Combined",
# "CareService",
# "Subtype",
# "ServiceType",
# "ServiceName",
# "Service_town",
# "Service_Postcode",
# "SP_number",
# "ServiceProvider",
# "Provided_by_Local_Authority",
# "ServiceStatus",
# "DateReg"]

# df = pd.melt(frame=df, id_vars=id_vars, var_name='Measure', value_name='Value')
# df.head()

,CSNumber,Combined_Service_,CaseNumber_Combined,CareService,Subtype,ServiceType,ServiceName,Service_town,Service_Postcode,SP_number,ServiceProvider,Provided_by_Local_Authority,ServiceStatus,DateReg,Measure,Value
0,CS2003000133,NaN,NaN,Day Care of Children,Day Care of Children (under 3s),Private,Sunflower Nursery 2,Clydebank,G81 4HT,SP2003001159,Sunflower Private Nursery Limited,NaN,Active,21/08/2002,SIMD_rank,969
1,CS2003000135,NaN,NaN,Child Minding,NaN,Private,"Gray, Alison",Glasgow,NaN,SP2003900012,"Gray, Alison",NaN,Active,23/10/2002,SIMD_rank,6925
2,CS2003000137,NaN,NaN,School Care Accommodation Service,Residential Special School,Voluntary or Not for Profit,East Park,Glasgow,G20 9TD,SP2003002355,East Park School,NaN,Active,01/04/2002,SIMD_rank,2110
3,CS2003000150,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Threshold Glasgow Day Opportunities,Glasgow,G40 1DA,SP2004005785,Church of Scotland Trading as Crossreach,NaN,Active,01/04/2002,SIMD_rank,1755
4,CS2003000152,NaN,NaN,Day Care of Children,Day Care of Children (under 3s),Private,Cherry Tree Nursery (Glasgow),Glasgow,G45 9QP,SP2003000007,Ann Fletcher and Jessica Jarvis trading as Che...,NaN,Active,29/05/2002,SIMD_rank,314

In [9]:
#df.Measure.unique()

array(['SIMD_rank', 'SIMD16_Decile', 'Datazone',
       'Integration_Authority_Name', 'TotalBeds', 'SingleBedrooms',
       'BedsInDoubleRooms', 'BedsInBedroomsFor3OrMore',
       'Dec17_Annual_Return_Submitted', 'CareHome_Main_Area_of_Care',
       'Council_Area_Name', 'Health_Board_Name', 'NumberStaff',
       'Registered_Places', 'Client_group', 'PublicList', 'RADScore',
       'GradeSpread', 'MinGrade', 'MaxGrade',
       'Publication_of_Latest_Grading', 'Quality_of_Information',
       'Quality_of_Care_and_Support', 'Quality_of_Environment',
       'Quality_of_Staffing', 'Quality_of_Mgmt_and_Lship',
       'KQ_Support_Wellbeing', 'KQ_Care_and_Support_Planning',
       'KQ_Setting', 'KQ_Staff_Team', 'KQ_Leadership',
       'Comb_Eval_CareSupport_Wellbeing',
       'Comb_Eval_CareSupport_Planning', 'Comb_Eval_Setting_Env',
       'Comb_Eval_Staff_StaffTeam', 'Comb_Eval_Leadership_ML',
       'MinGrade_change', 'CS_Wellbeing_change', 'CS_Planning_change',
       'Setting_change', 'Staff_change', 'Leadership_change',
       'Complnt_upheld_or_partially_1617',
       'Complnt_upheld_or_partially_1718',
       'Complnt_upheld_or_partially_1819', 'Enforcements_issued_1617',
       'Enforcements_issued_1718', 'Enforcements_issued_1819',
       'any_requirements_1617', 'any_requirements_1718',
       'any_requirements_1819', 'Count any reqs 1617',
       'Count any reqs 1718', 'Count any reqs 1819',
       'Last_inspection_Date', 'first_date_1718', 'first_case_1718',
       'first_recs_1718', 'first_reqs_1718', 'second_date_1718',
       'second_case_1718', 'second_recs_1718', 'second_reqs_1718',
       'third_date_1718', 'third_case_1718', 'third_recs_1718',
       'third_reqs_1718', 'first_date_1819', 'first_case_1819',
       'first_recs_1819', 'first_reqs_1819', 'second_date_1819',
       'second_case_1819', 'second_recs_1819', 'second_reqs_1819',
       'third_date_1819', 'third_case_1819', 'third_recs_1819',
       'third_reqs_1819', 'fourth_date_1819', 'fourth_case_1819',
       'fourth_recs_1819', 'fourth_reqs_1819'], dtype=object)