In [1]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv('MDSF_data.csv', encoding = "ISO-8859-1")

servicetypes = ["Support Service", "Care Home Service", "Offender Accommodation Service", "Housing Support Service"] 

df = df[df['CareService'].isin(servicetypes)].drop(["Address_line_1","Address_line_2","Address_line_3", "Address_line_4","ManagerName", "Service_Phone_Number", "Eforms_email_address", "Date_Reg"], axis=1)

In [28]:
df.head()

,CSNumber,Combined_Service_,CaseNumber_Combined,CareService,Subtype,ServiceType,ServiceName,Service_town,Service_Postcode,SP_number,...,second_recs_1819,second_reqs_1819,third_date_1819,third_case_1819,third_recs_1819,third_reqs_1819,fourth_date_1819,fourth_case_1819,fourth_recs_1819,fourth_reqs_1819
3,CS2003000150,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Threshold Glasgow Day Opportunities,Glasgow,G40 1DA,SP2004005785,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CS2003000153,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Aviv Club,Glasgow,G46 6LD,SP2005007546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CS2003000161,NaN,NaN,Care Home Service,Learning Disabilities,Voluntary or Not for Profit,Richmondhill House,Aberdeen,AB15 5EP,SP2003000011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CS2003000164,NaN,NaN,Care Home Service,Older People,Voluntary or Not for Profit,Ruthrieston House,Aberdeen,AB10 7LN,SP2003000011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CS2003000168,NaN,NaN,Care Home Service,Mental Health Problems,Voluntary or Not for Profit,Arrdeir,Aberdeen,AB15 7PJ,SP2003000011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
id_vars = ["CSNumber", 
"Combined_Service_",
"CaseNumber_Combined",
"CareService",
"Subtype",
"ServiceType",
"ServiceName",
"Service_town",
"Service_Postcode",
"SP_number",
"ServiceProvider",
"Provided_by_Local_Authority",
"ServiceStatus",
"DateReg"]

df = pd.melt(frame=df, id_vars=id_vars, var_name='Measure', value_name='Value')
df.head()

,CSNumber,Combined_Service_,CaseNumber_Combined,CareService,Subtype,ServiceType,ServiceName,Service_town,Service_Postcode,SP_number,ServiceProvider,Provided_by_Local_Authority,ServiceStatus,DateReg,measure,value
0,CS2003000150,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Threshold Glasgow Day Opportunities,Glasgow,G40 1DA,SP2004005785,Church of Scotland Trading as Crossreach,NaN,Active,01/04/2002,SIMD_rank,1755
1,CS2003000153,NaN,NaN,Support Service,Other than Care at home,Voluntary or Not for Profit,Aviv Club,Glasgow,G46 6LD,SP2005007546,Jewish Care Scotland,NaN,Active,01/04/2002,SIMD_rank,6281
2,CS2003000161,NaN,NaN,Care Home Service,Learning Disabilities,Voluntary or Not for Profit,Richmondhill House,Aberdeen,AB15 5EP,SP2003000011,"Aberdeen Association of Social Service, a comp...",NaN,Active,01/04/2002,SIMD_rank,6817
3,CS2003000164,NaN,NaN,Care Home Service,Older People,Voluntary or Not for Profit,Ruthrieston House,Aberdeen,AB10 7LN,SP2003000011,"Aberdeen Association of Social Service, a comp...",NaN,Active,01/04/2002,SIMD_rank,6177
4,CS2003000168,NaN,NaN,Care Home Service,Mental Health Problems,Voluntary or Not for Profit,Arrdeir,Aberdeen,AB15 7PJ,SP2003000011,"Aberdeen Association of Social Service, a comp...",NaN,Active,01/04/2002,SIMD_rank,6427